package view;

import javax.swing.table.DefaultTableModel;
import controller.ItensVendaCRUD;
import model.ItensVenda;
import java.util.ArrayList;
import controller.ProdutoCRUD;
import model.Produtos;
/**
 *
 * @author thiago
 */
public class TelaListarItensVenda extends javax.swing.JFrame {
       
    DefaultTableModel tableItens = new DefaultTableModel();
    
    ItensVendaCRUD itemAcao = new ItensVendaCRUD();
    ArrayList<ItensVenda> itens = new ArrayList<>();
    ProdutoCRUD prodAcao = new ProdutoCRUD();
    Produtos prod = new Produtos();
    ArrayList<Produtos> prods = new ArrayList<>();
    
    /**
     * Creates new form TelaListarItensVenda
     */
    public TelaListarItensVenda(int idVenda) {
        initComponents();
        
        this.setLocationRelativeTo(null); //faz a tela iniciar no centro
        
        tableItens = (DefaultTableModel) tableItensVenda.getModel();
        tableItens.setNumRows(0);
                
        itens = itemAcao.listarItensVenda(idVenda); //busca os itens da respectiva venda selecionada
        buscarProdItemVenda();
        listarItensVenda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableItensVenda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Valor Unt", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableItensVenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void listarItensVenda(){ //busca os itens da respectiva venda
        for(int i = 0; i < itens.size(); i++){
            tableItens.addRow(new Object[]{
                prods.get(i).getNomeProd(),
                itens.get(i).getQtd(),
                itens.get(i).getVlrUn(),
                itens.get(i).getVlrTotal()
            });
        }
    }
    
    public void buscarProdItemVenda(){ //busca os produtos inseridos como itens de uma venda
        for(int i = 0; i<itens.size(); i++){
            prod = prodAcao.pesquisarProd(itens.get(i).getIdProd());
            prods.add(prod);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListarItensVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListarItensVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListarItensVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListarItensVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListarItensVenda(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableItensVenda;
    // End of variables declaration//GEN-END:variables
}
