package view;

import model.Pagamentos;
import controller.PagamentoCRUD;
import java.util.ArrayList;
import controller.ClienteCRUD;
import java.text.SimpleDateFormat;
import model.Clientes;
import java.util.Date;
import model.Vendas;
import controller.VendaCRUD;
import controller.ItensVendaCRUD;
import model.ItensVenda;
import controller.ProdutoCRUD;
import java.text.DecimalFormat;

/**
 *
 * @author thiago
 */
public class TelaFecharVenda extends javax.swing.JFrame {

    PagamentoCRUD pagAcao = new PagamentoCRUD();
    ArrayList<Pagamentos> pags = new ArrayList<>();
    ClienteCRUD cliAcao = new ClienteCRUD();
    ArrayList<Clientes> clientes = new ArrayList<>();
    ArrayList<ItensVenda> itens = new ArrayList<>();
    Vendas venda = new Vendas();
    VendaCRUD vendaAcao = new VendaCRUD();
    ItensVendaCRUD itemAcao = new ItensVendaCRUD();
    ProdutoCRUD prodAcao = new ProdutoCRUD();
    
    DecimalFormat df = new DecimalFormat("0.00");

    TelaVenda telaVenda;

    String dataCompleta;
    double quantia;

    /**
     * Creates new form TelaFecharVenda
     */
    public TelaFecharVenda() {
        initComponents();

        this.setLocationRelativeTo(null); //faz a tela iniciar no centro
        this.setResizable(false); // .setResizable => premite ou não modificar o tamanho da tela

        listarMetodosPag();
        listarClientes();
        data();

        fieldQuantia.requestFocus();
    }

    public void listarMetodosPag() {
        pags = pagAcao.listarPags();

        for (int i = 0; i < pags.size(); i++) {
            comboMetodoPag.addItem(pags.get(i).getFormaPag());
        }
    }

    public void listarClientes() {
        clientes = cliAcao.listarClientes();

        for (int i = 0; i < clientes.size(); i++) {
            comboCliente.addItem(clientes.get(i).getNome());
        }
    }

    public void data() {
        Date data = new Date();

        SimpleDateFormat df = new SimpleDateFormat("yyyy/MM/dd");

        dataCompleta = df.format(data).replaceAll("/", "");
    }

    //transferir dados de uma tela para outra sem ser pelo construtor
    public void transferirDados(Vendas venda, ArrayList<ItensVenda> itens, TelaVenda telaVenda) {
        this.venda = venda;
        this.telaVenda = telaVenda;

        for (int i = 0; i < itens.size(); i++) {
            ItensVenda item = new ItensVenda();

            item.setIdProd(itens.get(i).getIdProd());
            item.setIdVenda(itens.get(i).getIdVenda());
            item.setQtd(itens.get(i).getQtd());
            item.setVlrTotal(itens.get(i).getVlrTotal());
            item.setVlrUn(itens.get(i).getVlrUn());

            this.itens.add(item);
        }

        fieldVlrTotal.setText(String.valueOf(venda.getValorTotal()));
    }

    public void verificarMetodoPagamento() { //verifica qual o método de pagamento escolhido
        String metodoPag = comboMetodoPag.getSelectedItem().toString();

        //verifica qual método de pagamento foi o escolhido e seta com o id do respectivo metodo
        for (int i = 0; i < pags.size(); i++) {
            if (pags.get(i).getFormaPag().equalsIgnoreCase(metodoPag)) {
                venda.setIdPag(pags.get(i).getIdPag());
            }
        }
    }

    public void verificarCliente() { //verifica qual o cliente escolhido
        String cliente = comboCliente.getSelectedItem().toString();

        //verifica qual o cliente escolhido e seta com o id do respectivo cliente
        for (int i = 0; i < clientes.size(); i++) {
            if (clientes.get(i).getNome().equalsIgnoreCase(cliente)) {
                venda.setIdCli(clientes.get(i).getId());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelQuantia = new javax.swing.JLabel();
        labelMetodoPag = new javax.swing.JLabel();
        comboMetodoPag = new javax.swing.JComboBox<>();
        labelTotalProdutos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelobrigado = new javax.swing.JLabel();
        fieldQuantia = new javax.swing.JTextField();
        labelTroco = new javax.swing.JLabel();
        fieldTroco = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        fieldVlrTotal = new javax.swing.JTextField();
        labelTroco1 = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelQuantia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelQuantia.setText("Quantia");

        labelMetodoPag.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelMetodoPag.setText("Selecione o Método de Pagamento");

        labelTotalProdutos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTotalProdutos.setText("Total dos Produtos");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        labelobrigado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelobrigado.setForeground(new java.awt.Color(255, 255, 255));
        labelobrigado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelobrigado.setText("OBRIGADO, VOLTE SEMPRE!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(labelobrigado)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelobrigado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        fieldQuantia.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        fieldQuantia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldQuantiaFocusLost(evt);
            }
        });
        fieldQuantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQuantiaActionPerformed(evt);
            }
        });

        labelTroco.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTroco.setText("Troco");

        fieldTroco.setEditable(false);
        fieldTroco.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        btnFinalizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        fieldVlrTotal.setEditable(false);
        fieldVlrTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        labelTroco1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTroco1.setText("Cliente");

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMetodoPag, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotalProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnFinalizar)
                        .addComponent(labelTroco1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldTroco, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(fieldVlrTotal)
                            .addComponent(comboMetodoPag, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldQuantia)
                            .addComponent(comboCliente, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalProdutos)
                    .addComponent(fieldVlrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetodoPag)
                    .addComponent(comboMetodoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantia)
                    .addComponent(fieldQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTroco))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTroco1)
                    .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(btnCancelar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        venda.setData(dataCompleta);

        verificarMetodoPagamento();
        verificarCliente();

        vendaAcao.salvarVenda(venda);
        itemAcao.salvarItens(itens);
        prodAcao.baixarEstoqueVenda(itens);

        //chamando os métodos da TelaVenda através da própria instancia da tela recebida no método transferirDados
        telaVenda.limparCampos();
        telaVenda.itemAcao.excluirTodosItens();
        telaVenda.idVenda();

        this.dispose();

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void fieldQuantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQuantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQuantiaActionPerformed

    private void fieldQuantiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldQuantiaFocusLost
        try {
            quantia = Double.parseDouble(fieldQuantia.getText());

            double troco = quantia - this.venda.getValorTotal();
            fieldTroco.setText(df.format(troco));

        } catch (Exception erro) {
            System.out.println("Campos Vazios para o Cálculo. Erro: " + erro);
        }
    }//GEN-LAST:event_fieldQuantiaFocusLost

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFecharVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFecharVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFecharVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFecharVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFecharVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JComboBox<String> comboMetodoPag;
    private javax.swing.JTextField fieldQuantia;
    private javax.swing.JTextField fieldTroco;
    private javax.swing.JTextField fieldVlrTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMetodoPag;
    private javax.swing.JLabel labelQuantia;
    private javax.swing.JLabel labelTotalProdutos;
    private javax.swing.JLabel labelTroco;
    private javax.swing.JLabel labelTroco1;
    private javax.swing.JLabel labelobrigado;
    // End of variables declaration//GEN-END:variables
}
