package view;

import javax.swing.JOptionPane;
import controller.ProdutoCRUD;
import model.Produtos;
import controller.VendaCRUD;
import controller.ItensVendaCRUD;
import java.awt.Point;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import model.ItensVenda;
import model.Vendas;
import model.Funcionarios;
import java.text.DecimalFormat;

/**
 *
 * @author thiago
 */
public class TelaVenda extends javax.swing.JFrame {

    int qtd, qtdItens, linhaSelec;
    String codProd;
    double vlrParcial;

    ProdutoCRUD prodAcao = new ProdutoCRUD();
    Produtos prod = new Produtos();
    VendaCRUD vendaAcao = new VendaCRUD();
    ItensVendaCRUD itemAcao = new ItensVendaCRUD();
    Vendas venda = new Vendas();
    Funcionarios func = new Funcionarios();

    DefaultTableModel table = new DefaultTableModel();
    DecimalFormat df = new DecimalFormat("0.00");

    ArrayList<Produtos> prods = new ArrayList<>();
    ArrayList<ItensVenda> itens = new ArrayList<>();

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH); //Deixa a tela no tamanho maximizado
        fieldProd.requestFocus(); //joga o foco para o fieldProd

        idVenda();

        table = (DefaultTableModel) tableItens.getModel();
        table.setRowCount(0);

        itemAcao.excluirTodosItens();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTopo = new javax.swing.JPanel();
        labelDescProd = new javax.swing.JLabel();
        panelPrecoUn = new javax.swing.JPanel();
        labelDescVlUn = new javax.swing.JLabel();
        labelVlUn = new javax.swing.JLabel();
        panelQtd = new javax.swing.JPanel();
        labelDescQtd = new javax.swing.JLabel();
        labelQtd = new javax.swing.JLabel();
        panelVlParcial = new javax.swing.JPanel();
        labelDescVlParcial = new javax.swing.JLabel();
        labelVlParcial = new javax.swing.JLabel();
        panelLogo = new javax.swing.JPanel();
        labelF2 = new javax.swing.JLabel();
        labelF3 = new javax.swing.JLabel();
        labelF9 = new javax.swing.JLabel();
        labelEnter = new javax.swing.JLabel();
        labelF4 = new javax.swing.JLabel();
        labelF10 = new javax.swing.JLabel();
        panelQtdItens = new javax.swing.JPanel();
        labelDescQtdItens = new javax.swing.JLabel();
        labelQtdItens = new javax.swing.JLabel();
        panelQtdItens1 = new javax.swing.JPanel();
        labelDescTotal = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        panelDescProd = new javax.swing.JPanel();
        labelProd = new javax.swing.JLabel();
        fieldProd = new javax.swing.JTextField();
        panelRodape = new javax.swing.JPanel();
        labelDesenv = new javax.swing.JLabel();
        labelDescAtend = new javax.swing.JLabel();
        labelAtend = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItens = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTopo.setBackground(new java.awt.Color(102, 153, 255));
        panelTopo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDescProd.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelDescProd.setForeground(new java.awt.Color(255, 255, 255));
        labelDescProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescProd.setText("CAIXA DISPONÍVEL");

        javax.swing.GroupLayout panelTopoLayout = new javax.swing.GroupLayout(panelTopo);
        panelTopo.setLayout(panelTopoLayout);
        panelTopoLayout.setHorizontalGroup(
            panelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDescProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTopoLayout.setVerticalGroup(
            panelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopoLayout.createSequentialGroup()
                .addComponent(labelDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelPrecoUn.setBackground(new java.awt.Color(102, 153, 255));
        panelPrecoUn.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDescVlUn.setForeground(new java.awt.Color(255, 255, 255));
        labelDescVlUn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescVlUn.setText("Valor Unitário");

        labelVlUn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelVlUn.setForeground(new java.awt.Color(255, 255, 255));
        labelVlUn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPrecoUnLayout = new javax.swing.GroupLayout(panelPrecoUn);
        panelPrecoUn.setLayout(panelPrecoUnLayout);
        panelPrecoUnLayout.setHorizontalGroup(
            panelPrecoUnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrecoUnLayout.createSequentialGroup()
                .addGroup(panelPrecoUnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrecoUnLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(labelDescVlUn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(panelPrecoUnLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelVlUn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPrecoUnLayout.setVerticalGroup(
            panelPrecoUnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrecoUnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDescVlUn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelVlUn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelQtd.setBackground(new java.awt.Color(102, 153, 255));
        panelQtd.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDescQtd.setForeground(new java.awt.Color(255, 255, 255));
        labelDescQtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescQtd.setText("Quantidade");

        labelQtd.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelQtd.setForeground(new java.awt.Color(255, 255, 255));
        labelQtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelQtdLayout = new javax.swing.GroupLayout(panelQtd);
        panelQtd.setLayout(panelQtdLayout);
        panelQtdLayout.setHorizontalGroup(
            panelQtdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQtdLayout.createSequentialGroup()
                .addGroup(panelQtdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQtdLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelDescQtd, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                    .addGroup(panelQtdLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(labelQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34)))
                .addContainerGap())
        );
        panelQtdLayout.setVerticalGroup(
            panelQtdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQtdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDescQtd)
                .addGap(5, 5, 5)
                .addComponent(labelQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelVlParcial.setBackground(new java.awt.Color(102, 153, 255));
        panelVlParcial.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDescVlParcial.setForeground(new java.awt.Color(255, 255, 255));
        labelDescVlParcial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescVlParcial.setText("Valor Parcial");

        labelVlParcial.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelVlParcial.setForeground(new java.awt.Color(255, 255, 255));
        labelVlParcial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelVlParcialLayout = new javax.swing.GroupLayout(panelVlParcial);
        panelVlParcial.setLayout(panelVlParcialLayout);
        panelVlParcialLayout.setHorizontalGroup(
            panelVlParcialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVlParcialLayout.createSequentialGroup()
                .addGroup(panelVlParcialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVlParcialLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(labelDescVlParcial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(panelVlParcialLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(labelVlParcial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(82, 82, 82))
        );
        panelVlParcialLayout.setVerticalGroup(
            panelVlParcialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVlParcialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDescVlParcial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelVlParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelLogo.setBackground(new java.awt.Color(255, 255, 255));
        panelLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelF2.setForeground(new java.awt.Color(0, 0, 0));
        labelF2.setText("F2 - Fechar venda");

        labelF3.setForeground(new java.awt.Color(0, 0, 0));
        labelF3.setText("F3 - Cancelar venda");

        labelF9.setForeground(new java.awt.Color(0, 0, 0));
        labelF9.setText("F9 - Cancelar produto");

        labelEnter.setForeground(new java.awt.Color(0, 0, 0));
        labelEnter.setText("Enter - Adicionar produto");

        labelF4.setForeground(new java.awt.Color(0, 0, 0));
        labelF4.setText("F11 - Sair");

        labelF10.setForeground(new java.awt.Color(0, 0, 0));
        labelF10.setText("F10 - Procurar Produto");

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogoLayout.createSequentialGroup()
                        .addComponent(labelEnter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelF4))
                    .addGroup(panelLogoLayout.createSequentialGroup()
                        .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelF9)
                            .addComponent(labelF2))
                        .addGap(33, 33, 33)
                        .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelF3)
                            .addComponent(labelF10))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelF2)
                    .addComponent(labelF3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelF9)
                    .addComponent(labelF10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnter)
                    .addComponent(labelF4))
                .addGap(19, 19, 19))
        );

        panelQtdItens.setBackground(new java.awt.Color(102, 153, 255));
        panelQtdItens.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDescQtdItens.setForeground(new java.awt.Color(255, 255, 255));
        labelDescQtdItens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescQtdItens.setText("Quantidade de Itens");

        labelQtdItens.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelQtdItens.setForeground(new java.awt.Color(255, 255, 255));
        labelQtdItens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelQtdItensLayout = new javax.swing.GroupLayout(panelQtdItens);
        panelQtdItens.setLayout(panelQtdItensLayout);
        panelQtdItensLayout.setHorizontalGroup(
            panelQtdItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQtdItensLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(panelQtdItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQtdItensLayout.createSequentialGroup()
                        .addComponent(labelDescQtdItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQtdItensLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(labelQtdItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(130, 130, 130))))
        );
        panelQtdItensLayout.setVerticalGroup(
            panelQtdItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQtdItensLayout.createSequentialGroup()
                .addComponent(labelDescQtdItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelQtdItens1.setBackground(new java.awt.Color(102, 153, 255));
        panelQtdItens1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDescTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelDescTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelDescTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescTotal.setText("Total Geral");

        labelTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelQtdItens1Layout = new javax.swing.GroupLayout(panelQtdItens1);
        panelQtdItens1.setLayout(panelQtdItens1Layout);
        panelQtdItens1Layout.setHorizontalGroup(
            panelQtdItens1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQtdItens1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelQtdItens1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQtdItens1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(labelDescTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQtdItens1Layout.createSequentialGroup()
                        .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44))))
        );
        panelQtdItens1Layout.setVerticalGroup(
            panelQtdItens1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQtdItens1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDescTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelDescProd.setBackground(new java.awt.Color(102, 153, 255));
        panelDescProd.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelProd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelProd.setForeground(new java.awt.Color(255, 255, 255));
        labelProd.setText("QTD * COD. PRODUTO");

        javax.swing.GroupLayout panelDescProdLayout = new javax.swing.GroupLayout(panelDescProd);
        panelDescProd.setLayout(panelDescProdLayout);
        panelDescProdLayout.setHorizontalGroup(
            panelDescProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDescProdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelProd)
                .addContainerGap())
        );
        panelDescProdLayout.setVerticalGroup(
            panelDescProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        fieldProd.setBackground(new java.awt.Color(255, 255, 153));
        fieldProd.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        fieldProd.setForeground(new java.awt.Color(0, 0, 51));
        fieldProd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldProd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fieldProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldProdActionPerformed(evt);
            }
        });
        fieldProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldProdKeyPressed(evt);
            }
        });

        panelRodape.setBackground(new java.awt.Color(102, 153, 255));
        panelRodape.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDesenv.setForeground(new java.awt.Color(255, 255, 255));
        labelDesenv.setText("Desenvolvido por: Thiago M. Joaquim");

        labelDescAtend.setForeground(new java.awt.Color(255, 255, 255));
        labelDescAtend.setText("Atendente:");

        labelAtend.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRodapeLayout = new javax.swing.GroupLayout(panelRodape);
        panelRodape.setLayout(panelRodapeLayout);
        panelRodapeLayout.setHorizontalGroup(
            panelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDesenv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(105, 105, 105)
                .addComponent(labelDescAtend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panelRodapeLayout.setVerticalGroup(
            panelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesenv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDescAtend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAtend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tableItens.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tableItens.setForeground(new java.awt.Color(0, 0, 0));
        tableItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Descrição", "Vlr Unt", "Qtd", "Vlr total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableItensMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableItens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelVlParcial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(panelPrecoUn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelQtdItens1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelQtdItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addComponent(panelTopo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(panelDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldProd)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelQtdItens1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelPrecoUn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelVlParcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDescProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldProd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldProdKeyPressed
        //verificando as teclas pressionadas
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) { //adiciona o item
            try {
                int pos = fieldProd.getText().indexOf("*"); //pegando a posição do caractere *

                qtd = Integer.parseInt(fieldProd.getText().substring(0, pos)); //pegando os caracteres até o *
                codProd = fieldProd.getText().substring((pos + 1)); //pegando os caracteres a partir do *

                prod = prodAcao.pesquisarCodProd(codProd); //pesquisando produto pelo código

                if (prod.getIdProd() != 0) {
                    //df.format está convertendo para duas casas decimais
                    vlrParcial = Double.parseDouble(df.format(qtd * prod.getVlrUnVenda()).replace(",", "."));

                    //adicionando item no array list
                    itemAcao.adicionarItem(prod, qtd, venda.getId());

                    atualizarCampoTotal();

                    //listando o item na tabela
                    listarItensTabela();

                    //atualizando os campos dos labels
                    labelVlUn.setText(String.valueOf(prod.getVlrUnVenda()));
                    labelQtd.setText(String.valueOf(qtd));
                    labelVlParcial.setText(String.valueOf(vlrParcial));
                    labelDescProd.setText(prod.getDescProd().toUpperCase());
                    atualizarCampoTotalItem();
                    atualizarCampoTotal();

                    //rolando o scroll para baixo automaticamente
                    int max = jScrollPane2.getVerticalScrollBar().getMaximum(); //pega o ponto máximo do scrollBar
                    jScrollPane2.getViewport().setViewPosition(new Point(0, max)); //seta o ponto onde o ScrollBar deve estar

                    //limpando o field de entrada
                    fieldProd.setText(null);

                } else {
                    JOptionPane.showMessageDialog(null, "Produto Não Encontrado");
                }

            } catch (Exception ex) {
                System.out.println("Erro de inserção de produto: " + ex);
                JOptionPane.showMessageDialog(null, "O formato de inserção deve ser qtd*código do produto");
            }
        }

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_F2) { //fecha a venda
            TelaFecharVenda tela = new TelaFecharVenda();

            venda.setValorTotal(itemAcao.valorTotalItens());

            //o this passa a própria instância dessa tela, para que a outra tela possa acessar os métodos e atributos
            //sem criar ouytra instância, para que os efeitos sejam feitos nessa mesma tela
            tela.transferirDados(venda, itens, this);
            tela.setVisible(true);
        }

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_F3) { //cancela a venda
            int op = JOptionPane.showConfirmDialog(null, "Deseja cancelar a Venda?");

            if (op == 0) { //0 == sim

                itemAcao.excluirTodosItens();
                limparCampos();
                idVenda();
            }
        }

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_F9) { //cancela produto
            JOptionPane.showMessageDialog(null, "Clique duas vezes no produto na tabela para cancelá-lo");
        }

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_F10) { //procura um produto
            JOptionPane.showMessageDialog(null, "Clique duas vezes sobre o produto desejado");

            TelaListarProdutos tela = new TelaListarProdutos();

            tela.transferirDados(this); //o this está passando a instância dessa tela
            tela.setVisible(true);
        }

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_F11) { //sair
            int op = JOptionPane.showConfirmDialog(null, "Deseja sair do Sistema?");

            if (op == 0) {
                this.dispose();
                TelaLogin tela = new TelaLogin();
                tela.setVisible(true);
            }
        }
    }//GEN-LAST:event_fieldProdKeyPressed

    private void fieldProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldProdActionPerformed

    }//GEN-LAST:event_fieldProdActionPerformed

    private void tableItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableItensMouseClicked

        if (evt.getClickCount() == 2) { //verificando se o total de cliques é igual a 2
            int op = JOptionPane.showConfirmDialog(null, "Deseja excluir o Produto selecionado?");

            if (op == 0) { // 0 == sim
                int ind = tableItens.getSelectedRow();

                itemAcao.excluirItem(ind); //excluindo item dos arrays

                listarItensTabela();
                atualizarCampoTotal();
                atualizarCampoTotalItem();
            }
        }

        fieldProd.requestFocus();

    }//GEN-LAST:event_tableItensMouseClicked

    public void listarItensTabela() { //listando os itens na tabela
        table.setNumRows(0);

        prods = itemAcao.produtosItens(); //buscando os produtos adicionados como item
        itens = itemAcao.itens(); //buscando os itens adicionados

        qtdItens = 0;

        for (int i = 0; i < prods.size(); i++) {
            qtdItens++;

            table.addRow(new Object[]{
                qtdItens,
                prods.get(i).getDescProd(),
                prods.get(i).getVlrUnVenda(),
                itens.get(i).getQtd(),
                itens.get(i).getVlrTotal()
            });
        }
    }

    public void idVenda() {
        venda.setId(vendaAcao.buscarIdMax() + 1);
    }

    public void atualizarCampoTotalItem() {
        labelQtdItens.setText(String.valueOf(qtdItens));
    }

    public void atualizarCampoTotal() {
        labelTotal.setText(String.valueOf(itemAcao.valorTotalItens()));
    }

    public void limparCampos() {
        fieldProd.setText(null);
        labelDescProd.setText("CAIXA DISPONÍVEL");
        labelVlUn.setText(null);
        labelQtd.setText(null);
        labelVlParcial.setText(null);
        labelQtdItens.setText(null);
        labelTotal.setText(null);
        table.setNumRows(0);
    }

    public void escreverCampoCodProd(String cod) { //escreve o código do produto no field Prod quando foi pesquisado 
        //um produto pela tecla F10
        fieldProd.setText(fieldProd.getText() + cod);
    }

    public void transferirDados(Funcionarios func) { //usado para transferir dados emtre as telas sem precisar do construtor
        this.func = func;

        labelAtend.setText(this.func.getNome());

        venda.setIdFunc(this.func.getId());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldProd;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAtend;
    private javax.swing.JLabel labelDescAtend;
    private javax.swing.JLabel labelDescProd;
    private javax.swing.JLabel labelDescQtd;
    private javax.swing.JLabel labelDescQtdItens;
    private javax.swing.JLabel labelDescTotal;
    private javax.swing.JLabel labelDescVlParcial;
    private javax.swing.JLabel labelDescVlUn;
    private javax.swing.JLabel labelDesenv;
    private javax.swing.JLabel labelEnter;
    private javax.swing.JLabel labelF10;
    private javax.swing.JLabel labelF2;
    private javax.swing.JLabel labelF3;
    private javax.swing.JLabel labelF4;
    private javax.swing.JLabel labelF9;
    private javax.swing.JLabel labelProd;
    private javax.swing.JLabel labelQtd;
    private javax.swing.JLabel labelQtdItens;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelVlParcial;
    private javax.swing.JLabel labelVlUn;
    private javax.swing.JPanel panelDescProd;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelPrecoUn;
    private javax.swing.JPanel panelQtd;
    private javax.swing.JPanel panelQtdItens;
    private javax.swing.JPanel panelQtdItens1;
    private javax.swing.JPanel panelRodape;
    private javax.swing.JPanel panelTopo;
    private javax.swing.JPanel panelVlParcial;
    private javax.swing.JTable tableItens;
    // End of variables declaration//GEN-END:variables
}
