package view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Funcionarios;
import model.Enderecos;
import controller.FuncionariosCRUD;
import controller.EnderecosCRUD;
/**
 *
 * @author thiago
 */
public class TelaListarFuncionarios extends javax.swing.JFrame {
    
    DefaultTableModel table = new DefaultTableModel();
    ArrayList<Funcionarios> funcs = new ArrayList<>();
    ArrayList<Enderecos> ends = new ArrayList<>();
    FuncionariosCRUD funcAcao = new FuncionariosCRUD();
    EnderecosCRUD endAcao = new EnderecosCRUD();
    /**
     * Creates new form TelaListaFuncionarios
     */
    public TelaListarFuncionarios() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        listarFuncionarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableListarFuncs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableListarFuncs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "RG", "CPF", "Data Nascimento", "Salário", "Data Admissão", "Login", "Cargo", "Logradouro", "Número", "Complemento", "Bairro", "Cidade", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableListarFuncs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void listarFuncionarios(){
        table = (DefaultTableModel) tableListarFuncs.getModel();
        table.setNumRows(0);
        
        funcs = funcAcao.listarFuncs();
        
        for(int i=0; i< funcs.size(); i++){
            Enderecos end = new Enderecos();
            end = endAcao.pesquisarEnd(funcs.get(i).getIdEndereco());
            ends.add(end);
        }
        
        for(int i=0; i< funcs.size(); i++){
            table.addRow(new Object[]{
                funcs.get(i).getId(),
                funcs.get(i).getNome(),
                funcs.get(i).getRg(),
                funcs.get(i).getCpf(),
                funcs.get(i).getDataNasc(),
                funcs.get(i).getSalario(),
                funcs.get(i).getAdmissao(),
                funcs.get(i).getLogin(),
                funcs.get(i).getIdCargo(),
                ends.get(i).getLogradouro(),
                ends.get(i).getNum(),
                ends.get(i).getComplemento(),
                ends.get(i).getBairro(),
                ends.get(i).getCidade(),
                ends.get(i).getCep()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListarFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListarFuncs;
    // End of variables declaration//GEN-END:variables
}
